sentence: You know Zeus of Olympia (alias Jupiter) from Greece?
texts:
  - text: You are a young woman and have been in a close relation with this person?
  - text: "<b>Feeling weird?</b>"
  - text: Don't wander more, contact me at leda@queenofsparta.gr
  - text: Cheers. Leda.