sentence: You know Zeus of Olympia (alias Jupiter) originally from Greece?
texts:
  - text: You are a young woman and is or have been in a close relation with this person?
  - text: "<b>Not feeling ok?</b>"
  - text: Contact me at leda@queenofsparta.gr
  - text: Cheers. Leda.